import { useMemo, useState } from 'react';

import Head from 'next/head';
import Image from 'next/image';

import { AppBar, Box, Grid, Typography } from '@mui/material';

import ShapesSidebar from '@/components/DraggableArea';
import DrawingArea from '@/components/DrawingArea';
import SnapshotActionBar from '@/components/SnapshotActionBar';
import useDimensions from '@/hooks/useDimensions';
import { LinesProvider } from '@/hooks/useLines';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const [divRef, { width, height }] = useDimensions();
  const [divRef2, { width: width2, height: height2 }] = useDimensions();

  return (
    <>
      <Head>
        <title>Badminton Strategy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LinesProvider>
        <main>
          <Grid container sx={{ minHeight: '100vh' }}>
            <Grid item xs={12} sx={{ bgcolor: 'primary.main' }}>
              <Box p={1}>
                <Typography variant="h1">Badminton Strategy</Typography>
                <Typography variant="subtitle1">
                  こういうAPPがプレゼントとだと思いますか？　どういう贈物が好きでか？
                </Typography>
              </Box>
            </Grid>
            <Grid
              item
              xs={12}
              sm={8}
              sx={{ bgcolor: 'primary.main' }}
              ref={divRef}
            >
              <DrawingArea width={width} height={height} />
              <SnapshotActionBar />
            </Grid>
            <Grid
              item
              xs={12}
              sm={4}
              sx={{ bgcolor: 'primary.main' }}
              ref={divRef2}
            >
              <ShapesSidebar width={width2} height={height2} />
            </Grid>
            <Grid item xs={12}>
              <Box sx={{ bgcolor: 'warning.main' }}>Footer</Box>
            </Grid>
          </Grid>
        </main>
      </LinesProvider>
    </>
  );
}
